version: '3.7'
services:
  keycloak:
    image: openproject/community:11
    restart: always
    ports:
      - 8093:8080
    environment:
      - SECRET_KEY_BASE=secret
    volumes:
      - /var/openproject/pgdata
      - /var/openproject/assets
